version: '2'

services:
  golang-dev:
    container_name: golang-dev
    build:
      context: .
      dockerfile: Dockerfile
    image: yanhao/docker-golang-dev
    hostname: golang.dev
    volumes:
      - ssh_agent:/.ssh-agent
      - "${HOME}/.share:/home/docker/.share"
      - ./src:/src
    environment:
      - SSH_AUTH_SOCK=/.ssh-agent/proxy-socket
      - HISTFILE=/home/docker/.share/.zsh_history
      - GIT_AUTHOR_NAME=Yanhao Yang
      - GIT_AUTHOR_EMAIL=yanhao.yang@example.com
      - GIT_COMMITTER_NAME=Yanhao Yang
      - GIT_COMMITTER_EMAIL=yanhao.yang@example.com

  ssh-agent:
    image: yanhao/ssh-agent

  ingress:
    image: traefik
    command: --api --docker --docker.domain=localhost
    ports:
      - "80:80"
      - "8088:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml
    labels:
      - "traefik.frontend.rule=Host:dashboard.localhost"
      - "traefik.port=8080"
